pipeline {
    agent any

    environment {
        ELASTICSEARCH_DOCKER_IMAGE = "elasticsearch:8.16.0"
        KIBANA_DOCKER_IMAGE = "kibana:8.16.0"
        LOGSTASH_DOCKER_IMAGE = "logstash:8.16.0"
    }

    stages {
        stage('Check System Resources') {
            steps {
                script {                    
                    def freeMemory = sh(script: "free -m | awk 'NR==2 {print \$4}'", returnStdout: true).trim()
                    freeMemory = freeMemory.toInteger()                    
                    if (freeMemory < 4096) {
                        currentBuild.description = "Недостаточно памяти. Будет развёрнут только Elasticsearch."
                    } else {
                        currentBuild.description = "Памяти достаточно. Будет развёрнут ELK stack."
                    }
                }
            }
        }

        stage('Deploy Elasticsearch') {
            when {
                expression { 
                    return currentBuild.description.contains('Elasticsearch') 
                }
            }
            steps {
                script {
                    echo "Разворачиваем Elasticsearch..."
                    sh "docker run -d --name elasticsearch -e discovery.type=single-node -p 9200:9200 ${ELASTICSEARCH_DOCKER_IMAGE}"
                }
            }
        }

        stage('Deploy Full ELK Stack') {
            when {
                expression { 
                    return currentBuild.description.contains('ELK stack') 
                }
            }
            steps {
                script {
                    echo "Разворачиваем полный ELK stack (Elasticsearch, Logstash, Kibana)..."                    
                    sh "docker run -d --name elasticsearch -e discovery.type=single-node -p 9200:9200 ${ELASTICSEARCH_DOCKER_IMAGE}"                    
                    sh "docker run -d --name logstash -p 5044:5044 ${env.LOGSTASH_DOCKER_IMAGE}"
                    sh "docker run -d --name kibana -p 5601:5601 --link elasticsearch:elasticsearch ${KIBANA_DOCKER_IMAGE}"
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline завершен"
        }
    }
}
